#!/bin/bash

# this is a simple config for herbstluftwm

function hc() {
    herbstclient "$@"
}

hc emit_hook reload

# keep here, so reinitializing doesn't require reboot, just a log out
# actually, a log out doesn't restart everything - session state is saved
compton --config /home/kdd/.compton.conf -b
mpd
emacs --daemon=server
# --no-site-file --no-site-lisp -- these seem to prevent urxvt transparency set in .Xresources
# single server daemon; set -t or -c at emacsclient level in loadapps.sh

# start jack automatically
#/home/kdd/LTF/jack-start.sh

# 
xsetroot -solid '#5A8E3A'

# remove all existing keybindings
hc keyunbind --all

## Reference
## $Mod = Super (Window) Key
## Mod1 = Alt key

# define Mod4 as Super Key
Mod=Mod4

# superkey keybindings
hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close

# toggle pseudotile and float
hc keybind Mod1-p pseudotile toggle
hc keybind Mod1-f floating toggle

# load apps with my layout
hc keybind Mod1-Shift-l spawn ~/.config/herbstluftwm/loadapps.sh

# load apps with my trial layout
hc keybind Mod1-Control-l spawn ~/.config/herbstluftwm/try_layout.sh 

# application keybindings
hc keybind Mod1-Return spawn urxvt # transparent
hc keybind Mod1-Control-Return spawn urxvt +tr # not transparent
hc keybind Mod1-Shift-0 spawn mpv pvr:// --tv-device=/dev/video0 --osc=no --ao=jack,alsa --tv-chanlist=europe-west --tv-channel=E10
hc keybind Mod1-Shift-1 spawn mpv pvr:// --tv-device=/dev/video1 --osc=no --ao=jack,alsa --tv-chanlist=europe-west --tv-channel=SE12
hc keybind Mod1-Shift-a spawn ardour4
hc keybind Mod1-Control-a spawn audacity
hc keybind Shift-Control-a spawn amule
hc keybind Mod1-Shift-c spawn conkeror
hc keybind Mod1-Control-c spawn cadence
hc keybind Mod1-Shift-d spawn dmenu_run 
hc keybind Mod1-e spawn emacsclient -s server -nc # gui emacsclient
hc keybind Mod1-Shift-e spawn urxvt -e emacsclient -s server -t # terminal emacsclient
hc keybind Mod1-Shift-f spawn firefox
hc keybind Mod1-Control-f spawn foxitreader
hc keybind Mod1-Shift-g spawn gnumeric
hc keybind Control-Shift-g spawn gmrun
hc keybind Mod1-Control-g spawn gqview
hc keybind Mod1-Shift-h spawn hydrogen

hc keybind Mod1-Control-h emit_hook togglehidepanel

hc keybind Mod1-Shift-j chain . focus_monitor 0 . use guitarix . spawn qjackctl . sleep 3 . spawn guitarix . sleep 3 . spawn patchage # monitor 1 is on the left, 0 in the center and 2 on the right
hc keybind Mod1-Control-l spawn lingot # guitar tuner
hc keybind Mod1-Shift-m spawn pdfeditor
hc keybind Mod1-Shift-p spawn patchage
hc keybind Control-Shift-p spawn touch ~/.pomodoro_session # start/restart pymodoro
hc keybind Mod1-Control-p spawn rm ~/.pomodoro_session # stop pymodoro
hc keybind Mod1-Shift-u spawn uget-gtk
hc keybind Mod1-Shift-v spawn viewnior
hc keybind Mod1-Shift-x chain . use xfe . spawn xfe

# tags
#TAG_NAMES=( {1..9} )
TAG_NAMES=("browser" "emacs" "urxvt" "zen-mode" "xfe" "qemu-1" "qemu-2" "savannah" "guitarix" "mpv")

# optional tags
# "Hydrogen" "Rosegarden" "Ardour" 

TAG_KEYS=( {1..9} 0 )

hc rename default "${TAG_NAMES[0]}" || true
for i in ${!TAG_NAMES[@]} ; do
    hc add "${TAG_NAMES[$i]}"
    key="${TAG_KEYS[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible
hc keybind $Mod-Right use_index +1 --skip-visible
hc keybind $Mod-Left  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-space cycle_layout 1
hc keybind $Mod-u split vertical 0.5
hc keybind $Mod-o split horizontal 0.5
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

# resizing
RESIZESTEP=0.05
hc keybind $Mod-Control-h resize left +$RESIZESTEP
hc keybind $Mod-Control-j resize down +$RESIZESTEP
hc keybind $Mod-Control-k resize up +$RESIZESTEP
hc keybind $Mod-Control-l resize right +$RESIZESTEP

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 resize
hc mousebind $Mod-Button3 zoom

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-h focus left
hc keybind $Mod-j focus down
hc keybind $Mod-k focus up
hc keybind $Mod-l focus right
hc keybind $Mod-i jumpto urgent
hc keybind $Mod-Shift-h shift left
hc keybind $Mod-Shift-j shift down
hc keybind $Mod-Shift-k shift up
hc keybind $Mod-Shift-l shift right

# colors
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#565656'
hc set frame_bg_active_color '#345F0C'

hc set frame_border_width 1 #orig 1
hc set window_border_width 3 #orig 3
hc set window_border_inner_width 1 #orig 1
hc set window_border_normal_color '#454545'

# this is an important setting
hc set window_border_active_color '#747474'  #orig: '#9fbc00'  # hlwm green 

hc set always_show_frame 1 #orig 1
hc set frame_gap 6 #orig 4
# add overlapping window borders
hc set window_gap -2 #orig -2
hc set frame_padding 1 #orig 2
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1 #orig 1
hc set mouse_recenter_gap 0

# kdd transparency stuff, requires a compositor like xcompmgr
#hc set frame_bg_transparent 1 # leaves artifacts
hc set frame_normal_opacity 0
hc set frame_active_opacity 10 

# kdd
hc set focus_follows_mouse 1

# rules
hc unrule -F

# give focus to most common terminals
hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=off
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off

# automatically move programs to specific tags upon opening
hc rule class=Abiword tag=savannah index=101 focus=on
hc rule class=Amule tag=savannah index=0 focus=on
hc rule class=Ardour-4.2.0 tag=savannah index=0 focus=on
hc rule class=Audacity tag=savannah index=0 focus=on
hc rule class=Cadence.py tag=guitarix index=10 focus=on
hc rule class=Catia.py tag=savannah index=0 focus=on
hc rule class=Claudia_launcher.py tag=savannah index=0 focus=on
hc rule class=Conkeror tag=browser index=0110 focus=on
# use index=101 for all apps using the Documents tag if it is presplit like before
hc rule class=Gimp tag=savannah index=0 focus=on pseudotile=on
hc rule class=Gnumeric tag=savannah index=0 focus=on
hc rule class=GQview tag=savannah index=0 focus=on
hc rule class=FBReader tag=savannah index=0 focus=on

hc rule class=Firefox tag=browser index=0110 focus=on

hc rule class=Guitarix tag=guitarix index=01 focus=on # pseudotile=on
hc rule class=Hydrogen tag=savannah index=0 focus=on pseudotile=on
hc rule class=Lingot tag=guitarix index=01 focus=on pseudotile=on
hc rule class=mpv tag=mpv index=0 focus=on
hc rule class=Patchage tag=guitarix index=11 focus=on pseudotile=off
hc rule class=Pdfeditor tag=savannah index=0 focus=on
hc rule class=qjackctl tag=guitarix index=10 focus=on pseudotile=on

hc rule class=qemu-system-x86_64 tag=qemu-1 index=0 focus=off # with spice there won't be a visible window, so don't focus (switch) to the qemu-1 tag
hc rule class=Spicy title="spice display 1:0" tag=qemu-1 index=0 focus=on
hc rule class=Spicy title="spice display 2:0" tag=qemu-2 index=0 focus=on

hc rule class=Uget-gtk tag=savannah index=0 focus=on
hc rule class=Viewnior tag=savannah index=0 focus=on
hc rule class=Xfe tag=xfe index=0 focus=on

#hc rule class=Rosegarden tag=guitarix index=0 focus=on
#hc rule class=nightcode-Nightcode tag=Savannah index=0 focus=on
#hc rule class=nightmod-Nightmod tag=Savannah index=0 focus=on


# kdd
hc rule focus=on     # focus new clients by default, normally off

#hc load p2p '
#(split vertical:0.500000:1 (split horizontal:0.500000:1 (clients vertical:0) (clients vertical:0)) (split horizontal:0.500000:1 (clients vertical:0) (clients vertical:0)))
#' # load predefined layout

# seems a full screen is better, so commented out
#hc load Documents '
#(split horizontal:0.075000:1 (clients vertical:0) (split horizontal:0.925000:0 (split vertical:0.100000:1 (clients vertical:0) (split vertical:0.925000:0 (clients vertical:0) (clients vertical:0))) (clients vertical:0)))
#' # load predefined layout

#hc load urxvt '
#(split horizontal:0.500000:0 (clients vertical:0))
#'



hc load guitarix '
(split horizontal:0.500000:0 (clients vertical:0))
'

hc load zen-mode '
(split horizontal:0.300000:1 (clients vertical:0) (split horizontal:0.600000:0 (split vertical:0.120000:1 (clients vertical:0) (split vertical:0.800000:0 (clients vertical:0) (clients vertical:0))) (clients vertical:0)))
'

hc load urxvt '
(split horizontal:0.400000:0 (split horizontal:0.025000:1 (clients vertical:0) (split vertical:0.025000:1 (clients vertical:0) (split vertical:0.975000:0 (split vertical:0.333000:0 (clients vertical:0) (clients vertical:0)) (clients vertical:0)))) (split horizontal:0.025000:1 (clients vertical:0) (split horizontal:0.975000:0 (split vertical:0.975000:0 (split vertical:0.150000:1 (clients vertical:0) (clients vertical:0)) (clients vertical:0)) (clients vertical:0))))
' # load predefined layout

# load predefined layouts
hc load browser '
(split horizontal:0.750000:1 (split horizontal:0.050000:1 (clients vertical:0) (split vertical:0.100000:1 (clients vertical:0) (split vertical:0.850000:1 (clients vertical:0) (clients vertical:0)))) (split horizontal:0.125000:1 (clients vertical:0) (split horizontal:0.850000:1 (split vertical:0.025000:1 (clients vertical:0) (split vertical:0.350000:1 (clients vertical:0) (split vertical:0.150000:1 (clients vertical:0) (split vertical:0.900000:1 (clients vertical:0) (clients vertical:0))))) (clients vertical:0))))
' # load predefined layout

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
#hc set_monitors 1680x1050+0+0 1368x768+1680+0
# or simply:
hc detect_monitors

# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    $panel $monitor &
done
